[components]
[components.leo-fmt]
binaries = ["leo-fmt"]
[components.leo-fmt.versions]
[components.leo-fmt.versions."4.1.0"]
archive_url_template = "https://github.com/ProvableHQ/leo/releases/download/leo-fmt-v4.1.0/leo-fmt-v4.1.0-{target}.zip"
tag = "leo-fmt-v4.1.0"
[components.leo-fmt.versions."4.1.0".compat]
leo-lang = "4.1.0"
leo-lsp = "4.1.0"
[components.leo-fmt.versions."4.1.0".targets]
aarch64-apple-darwin = "sha256-rzNnLZDPmGxLx2eUxNLvYTxGNPovQi7YRukwQ6t5hPM="
x86_64-apple-darwin = "sha256-WIp68kvsQCvmuaHT3H7EutPPLHOzYqsP3VLu+BmY10M="
x86_64-unknown-linux-gnu = "sha256-/gmuCjes0EhLvQqbmZH3ch4Z6Y+bUQ5VRpgubKvVNL0="
[components.leo-fmt.versions."4.2.0"]
archive_url_template = "https://github.com/ProvableHQ/leo/releases/download/leo-fmt-v4.2.0/leo-fmt-v4.2.0-{target}.zip"
tag = "leo-fmt-v4.2.0"
[components.leo-fmt.versions."4.2.0".compat]
leo-lang = "4.2.0"
leo-lsp = "4.2.0"
[components.leo-fmt.versions."4.2.0".targets]
aarch64-apple-darwin = "sha256-mzT6yMHFLXk3+6s/TIKMfn5HLIJFC8ZUFZ4DFm1l/+c="
x86_64-apple-darwin = "sha256-OA8+YG/Y4krI0wkFP2u8yAxU77k1ENFpoOzWDuJLxF0="
x86_64-unknown-linux-gnu = "sha256-SLYACgvPz+/qoKHSILdwWT8SP7JLaXNvPEQ5Qh9ZTNw="
[components.leo-fmt.versions."4.3.1"]
archive_url_template = "https://github.com/ProvableHQ/leo/releases/download/leo-fmt-v4.3.1/leo-fmt-v4.3.1-{target}.zip"
tag = "leo-fmt-v4.3.1"
[components.leo-fmt.versions."4.3.1".compat]
leo-lang = "4.3.1"
leo-lsp = "4.3.1"
[components.leo-fmt.versions."4.3.1".targets]
aarch64-apple-darwin = "sha256-8xniQVZwSGhbXYBCFk5mst3zVA6HK7ckMYwik8mt19c="
x86_64-apple-darwin = "sha256-y790ukuAv2a6MGms1q92zIpnUo9+HeenJL9HsZqYmNA="
x86_64-unknown-linux-gnu = "sha256-Dsn1rheJ9jSbYDT3gsE5DlP7JiU5Pb/x+EoWcUog7Xk="
[components.leo-fmt.versions."4.3.2"]
archive_url_template = "https://github.com/ProvableHQ/leo/releases/download/leo-fmt-v4.3.2/leo-fmt-v4.3.2-{target}.zip"
tag = "leo-fmt-v4.3.2"
[components.leo-fmt.versions."4.3.2".compat]
leo-lang = "4.3.2"
leo-lsp = "4.3.2"
[components.leo-fmt.versions."4.3.2".targets]
aarch64-apple-darwin = "sha256-02XwOH4KxclK8LOfVk8mB06qVJeHhbl59H91rEwwmn4="
x86_64-apple-darwin = "sha256-rD0G1K5Ie5HPDYajd/He+JwJ+5jJe9+haQBrDVX+6uI="
x86_64-unknown-linux-gnu = "sha256-ASGipKbl8WOzC8TUoIEArvGvhbliyumHTvOFWImGxaI="
[components.leo-lang]
binaries = ["leo"]
[components.leo-lang.versions]
[components.leo-lang.versions."4.1.0"]
archive_url_template = "https://github.com/ProvableHQ/leo/releases/download/leo-lang-v4.1.0/leo-lang-v4.1.0-{target}.zip"
tag = "leo-lang-v4.1.0"
[components.leo-lang.versions."4.1.0".compat]
leo-fmt = "4.1.0"
leo-lsp = "4.1.0"
[components.leo-lang.versions."4.1.0".targets]
aarch64-apple-darwin = "sha256-KbqODSvnu4pe+4ctMUll8v5cSPLqndPP2J/aqfv4kPE="
x86_64-apple-darwin = "sha256-HckaYUqdmYzJiJuDuPp5p0YLT9RC36ElF0DoqbKF9ng="
x86_64-unknown-linux-gnu = "sha256-Hpy4/B+Ux22Gke8wiIGhBlrfhXw9AT+Bv0QwgG/Z5q0="
[components.leo-lang.versions."4.2.0"]
archive_url_template = "https://github.com/ProvableHQ/leo/releases/download/leo-lang-v4.2.0/leo-lang-v4.2.0-{target}.zip"
tag = "leo-lang-v4.2.0"
[components.leo-lang.versions."4.2.0".compat]
leo-fmt = "4.2.0"
leo-lsp = "4.2.0"
[components.leo-lang.versions."4.2.0".targets]
aarch64-apple-darwin = "sha256-hvRcC40jWTmtyeYCisPK25i1fOFQyiC462epWiJZSf8="
x86_64-apple-darwin = "sha256-SjeLNjpXSJXsqnDkRE9NfAe5BbBsZyzUFu9+E9HZhmI="
x86_64-unknown-linux-gnu = "sha256-4MXY/HdLfSmfatrW9QjZ+9A3rAIxlzcrVBwsVuyDIV0="
[components.leo-lang.versions."4.3.1"]
archive_url_template = "https://github.com/ProvableHQ/leo/releases/download/leo-lang-v4.3.1/leo-lang-v4.3.1-{target}.zip"
tag = "leo-lang-v4.3.1"
[components.leo-lang.versions."4.3.1".compat]
leo-fmt = "4.3.1"
leo-lsp = "4.3.1"
[components.leo-lang.versions."4.3.1".targets]
aarch64-apple-darwin = "sha256-dENDrV3Zw2KtD8XTrpCDg02ifCjqR8PmB3FDOGdBLVg="
x86_64-apple-darwin = "sha256-AsV+0t7Putfe8AjwMrLeBL+8sfInhHEj7aez/dR4U5I="
x86_64-unknown-linux-gnu = "sha256-ppIH4dlk3Z0jMQn0NJNEQRLxDrKRt/Ri6g9n/GD+k9g="
[components.leo-lang.versions."4.3.2"]
archive_url_template = "https://github.com/ProvableHQ/leo/releases/download/leo-lang-v4.3.2/leo-lang-v4.3.2-{target}.zip"
tag = "leo-lang-v4.3.2"
[components.leo-lang.versions."4.3.2".compat]
leo-fmt = "4.3.2"
leo-lsp = "4.3.2"
[components.leo-lang.versions."4.3.2".targets]
aarch64-apple-darwin = "sha256-sGRFiEGbSohO0OFndHI2+B8YYd84BJ3DggPQztRss1M="
x86_64-apple-darwin = "sha256-eSs4lvpf4kHUkNKx+Mw39WYV199tQtG6uglRnfaoBEs="
x86_64-unknown-linux-gnu = "sha256-PzvXjAdc2GQP90U/YpnzH11DES3Fdcnf8xXWd7cPbGI="
[components.leo-lsp]
binaries = ["leo-lsp"]
[components.leo-lsp.versions]
[components.leo-lsp.versions."4.0.2"]
archive_url_template = "https://github.com/ProvableHQ/leo/releases/download/leo-lsp-v4.0.2/leo-lsp-v4.0.2-{target}.zip"
tag = "leo-lsp-v4.0.2"
[components.leo-lsp.versions."4.0.2".targets]
aarch64-apple-darwin = "sha256-n0zYpKuQPzF8+kuBNk+itXx1E8WGmNhGfTXh9VnO1Hw="
x86_64-apple-darwin = "sha256-Gq0+A2W7OIA6YTaAPtcQg5elQNgy9SfsHXj2n8ONV9w="
x86_64-unknown-linux-gnu = "sha256-djrXyvontZne7Eb1+jqRIfw8yFUinBFuQIqb+GNuHRE="
[components.leo-lsp.versions."4.1.0"]
archive_url_template = "https://github.com/ProvableHQ/leo/releases/download/leo-lsp-v4.1.0/leo-lsp-v4.1.0-{target}.zip"
tag = "leo-lsp-v4.1.0"
[components.leo-lsp.versions."4.1.0".compat]
leo-fmt = "4.1.0"
leo-lang = "4.1.0"
[components.leo-lsp.versions."4.1.0".targets]
aarch64-apple-darwin = "sha256-E2adjKjN3daTZTpj34xNfS6iCweHdGyYgc9N6xbOo9w="
x86_64-apple-darwin = "sha256-Ygk5yu++G7L+ElVeNEdqqmtSciwoXO9jFmxTvfAeY5g="
x86_64-unknown-linux-gnu = "sha256-ROHtrbcmv81cZZgb2c6qEx5BO7Dkds7Gp1GxcnxQMrA="
[components.leo-lsp.versions."4.2.0"]
archive_url_template = "https://github.com/ProvableHQ/leo/releases/download/leo-lsp-v4.2.0/leo-lsp-v4.2.0-{target}.zip"
tag = "leo-lsp-v4.2.0"
[components.leo-lsp.versions."4.2.0".compat]
leo-fmt = "4.2.0"
leo-lang = "4.2.0"
[components.leo-lsp.versions."4.2.0".targets]
aarch64-apple-darwin = "sha256-TbXW37vg97UirtEF3xhsiRi4+CNdCyy8zDjod89LvOk="
x86_64-apple-darwin = "sha256-1T/ZuPeMymo7JNtWixQvyh6Gw8zkUfR0506aTro4ONc="
x86_64-unknown-linux-gnu = "sha256-IZri2OipAIA1t9nDePUQtwdS6+FkF1Beo4QbsDUqUN8="
[components.leo-lsp.versions."4.3.1"]
archive_url_template = "https://github.com/ProvableHQ/leo/releases/download/leo-lsp-v4.3.1/leo-lsp-v4.3.1-{target}.zip"
tag = "leo-lsp-v4.3.1"
[components.leo-lsp.versions."4.3.1".compat]
leo-fmt = "4.3.1"
leo-lang = "4.3.1"
[components.leo-lsp.versions."4.3.1".targets]
aarch64-apple-darwin = "sha256-VDOE71Yb/Yt0/oDoTs7D3rBqXLMeIYvTP81IjBtyJ+Y="
x86_64-apple-darwin = "sha256-EY3iql1XmSneW6C8EwsYu3qJxfwsiOQSjgDXrfKKc/s="
x86_64-unknown-linux-gnu = "sha256-0s0TwRRPWzG4/HIy5+KSCknaqOf3+S1OIdbO8Uv1fNs="
[components.leo-lsp.versions."4.3.2"]
archive_url_template = "https://github.com/ProvableHQ/leo/releases/download/leo-lsp-v4.3.2/leo-lsp-v4.3.2-{target}.zip"
tag = "leo-lsp-v4.3.2"
[components.leo-lsp.versions."4.3.2".compat]
leo-fmt = "4.3.2"
leo-lang = "4.3.2"
[components.leo-lsp.versions."4.3.2".targets]
aarch64-apple-darwin = "sha256-VCSQE3nUvTIDzbCGpDLIJo8/XD+Xz53KZdzFzh/Q9BI="
x86_64-apple-darwin = "sha256-dqZEkDdPiEcMZKbQ35bH7qUGxdXy1P2XDzF0a0CaNGQ="
x86_64-unknown-linux-gnu = "sha256-xdDKcFB+ouXWRazL+IGwYkG9B4CwKWIf30F95uvHl1k="

[latest]
leo-fmt = "4.3.2"
leo-lang = "4.3.2"
leo-lsp = "4.3.2"
