[components]
[components.leo-fmt]
binaries = ["leo-fmt"]
[components.leo-fmt.versions]
[components.leo-fmt.versions."4.1.0"]
archive_url_template = "https://github.com/ProvableHQ/leo/releases/download/leo-fmt-v4.1.0/leo-fmt-v4.1.0-{target}.zip"
tag = "leo-fmt-v4.1.0"
[components.leo-fmt.versions."4.1.0".compat]
leo-lang = "4.1.0"
leo-lsp = "4.1.0"
[components.leo-fmt.versions."4.1.0".targets]
aarch64-apple-darwin = "sha256-rzNnLZDPmGxLx2eUxNLvYTxGNPovQi7YRukwQ6t5hPM="
x86_64-apple-darwin = "sha256-WIp68kvsQCvmuaHT3H7EutPPLHOzYqsP3VLu+BmY10M="
x86_64-unknown-linux-gnu = "sha256-/gmuCjes0EhLvQqbmZH3ch4Z6Y+bUQ5VRpgubKvVNL0="
[components.leo-lang]
binaries = ["leo"]
[components.leo-lang.versions]
[components.leo-lang.versions."4.1.0"]
archive_url_template = "https://github.com/ProvableHQ/leo/releases/download/leo-lang-v4.1.0/leo-lang-v4.1.0-{target}.zip"
tag = "leo-lang-v4.1.0"
[components.leo-lang.versions."4.1.0".compat]
leo-fmt = "4.1.0"
leo-lsp = "4.1.0"
[components.leo-lang.versions."4.1.0".targets]
aarch64-apple-darwin = "sha256-KbqODSvnu4pe+4ctMUll8v5cSPLqndPP2J/aqfv4kPE="
x86_64-apple-darwin = "sha256-HckaYUqdmYzJiJuDuPp5p0YLT9RC36ElF0DoqbKF9ng="
x86_64-unknown-linux-gnu = "sha256-Hpy4/B+Ux22Gke8wiIGhBlrfhXw9AT+Bv0QwgG/Z5q0="
[components.leo-lsp]
binaries = ["leo-lsp"]
[components.leo-lsp.versions]
[components.leo-lsp.versions."4.0.2"]
archive_url_template = "https://github.com/ProvableHQ/leo/releases/download/leo-lsp-v4.0.2/leo-lsp-v4.0.2-{target}.zip"
tag = "leo-lsp-v4.0.2"
[components.leo-lsp.versions."4.0.2".targets]
aarch64-apple-darwin = "sha256-n0zYpKuQPzF8+kuBNk+itXx1E8WGmNhGfTXh9VnO1Hw="
x86_64-apple-darwin = "sha256-Gq0+A2W7OIA6YTaAPtcQg5elQNgy9SfsHXj2n8ONV9w="
x86_64-unknown-linux-gnu = "sha256-djrXyvontZne7Eb1+jqRIfw8yFUinBFuQIqb+GNuHRE="
[components.leo-lsp.versions."4.1.0"]
archive_url_template = "https://github.com/ProvableHQ/leo/releases/download/leo-lsp-v4.1.0/leo-lsp-v4.1.0-{target}.zip"
tag = "leo-lsp-v4.1.0"
[components.leo-lsp.versions."4.1.0".compat]
leo-fmt = "4.1.0"
leo-lang = "4.1.0"
[components.leo-lsp.versions."4.1.0".targets]
aarch64-apple-darwin = "sha256-E2adjKjN3daTZTpj34xNfS6iCweHdGyYgc9N6xbOo9w="
x86_64-apple-darwin = "sha256-Ygk5yu++G7L+ElVeNEdqqmtSciwoXO9jFmxTvfAeY5g="
x86_64-unknown-linux-gnu = "sha256-ROHtrbcmv81cZZgb2c6qEx5BO7Dkds7Gp1GxcnxQMrA="

[latest]
leo-fmt = "4.1.0"
leo-lang = "4.1.0"
leo-lsp = "4.1.0"
